Support for waiting on tcp port to open
shyim/testcontainer pull request #12
Opened 2024-07-15 22:21 UTC by dinamic

2024-07-15 22:22 UTC, dinamic commented on src/Wait/WaitForTcpPort.php
> +    protected function findContainerAddress(string $id): ?string
It might be a good idea to think on how to reuse this logic.

Maybe we could have a trait to be used by all implementations of the `WaitInterface` 🤔

2024-07-15 23:21 UTC, dinamic commented on src/Wait/WaitForTcpPortOpen.php
> +    private function findContainerAddress(string $id): string
It might be a good idea to think on how to reuse this logic.

Maybe we could have a trait to be used by all implementations of the `WaitInterface` 🤔

2024-07-16 02:09 UTC, dinamic commented on src/Wait/WaitForTcpPortOpen.php
> +    private function findContainerAddress(string $id): string
This has already been actioned on 🚀

2024-07-16 10:09 UTC, shyim requested changes

2024-07-16 10:09 UTC, shyim commented on src/Wait/WaitForTcpPortOpen.php
> +        if (@fsockopen(self::dockerContainerAddress(containerId: $id, networkName: $this->network), $this->port) === false) {
I think you will need to call fclose when connected otherwise a socket will be blocked until php process finished. As the main usage is in tests we can reach this fast I think

2024-07-16 10:10 UTC, shyim commented
Really thank you for the pull request ❤️

2024-07-16 10:43 UTC, dinamic commented on src/Wait/WaitForTcpPortOpen.php
> +        if (@fsockopen(self::dockerContainerAddress(containerId: $id, networkName: $this->network), $this->port) === false) {
I think if it's not assigned to a variable GC would clean it as soon as possible.

Let me know if you'd like me to capture the stream in a variable and `fclose()` it. Happy to do it, it just doesn't feel necessary.

2024-07-16 11:27 UTC, shyim commented on src/Wait/WaitForTcpPortOpen.php
> +        if (@fsockopen(self::dockerContainerAddress(containerId: $id, networkName: $this->network), $this->port) === false) {
You are right lol. Didn't know that. Thanks!

2024-07-16 11:28 UTC, merged